### ISSUE TITLE
Create an input fuction.

### ISSUE THREAD

**Issue by SebastianDahlin** [SebastianDahlin/zodiac#2]
Should be done in the development branch.
The function from the user must be handled. Should the user enter incorrect formatting etc, the function should prompt the user once again.
When correct formatting has been validated the input value should be returned.

**Comment by SebastianDahlin** [comment]
@Lerking Should be done in the development branch.

**Comment by Lerking** [comment]
Function input_zodiac returns DOB if date format is correct (MMDD).
Asks again otherwise.

**Comment by SebastianDahlin** [comment]
There is a project above where I created a kanban board!
Let's close the issues when we have created, ran and passed specific test cases for them!

**Comment by SebastianDahlin** [comment]
Created a test, ran it and input_zodiac works great :)
Nice done man!
